# Generated by Django 3.1.1 on 2020-10-06 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_album', models.CharField(max_length=255)),
                ('cover', models.ImageField(upload_to='images/')),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artists_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songs_title', models.CharField(max_length=255)),
                ('track', models.FileField(upload_to='tracks/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleForm.album')),
                ('artists', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='simpleForm.artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='simpleForm.artist'),
        ),
    ]
