# Generated by Django 3.1.1 on 2020-10-09 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleForm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musictrack',
            name='artists',
        ),
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleForm.artist'),
        ),
    ]
