# Generated by Django 3.1.1 on 2020-10-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleForm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musictrack',
            name='artists',
        ),
    ]
