# Generated by Django 3.1.1 on 2020-10-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleForm', '0002_auto_20201010_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
