# Generated by Django 3.1.1 on 2020-10-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleForm', '0003_auto_20201014_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
