# Generated by Django 3.1.1 on 2020-10-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleForm', '0004_auto_20201015_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
