# Generated by Django 3.1.1 on 2020-10-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleForm', '0005_auto_20201015_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
